config/routes.rb
Rails.application.routes.draw do
  get 'lista_usuarios/index'

  root to:"zombies#index"

devise_scope :admin do
  	get 'lista_usuarios/index'
  end  
    
  
devise_for :admins, controllers: {
	sessions: 'admins/sessions'
}

  devise_for :users, controllers: {
    session: 'users/session'
  }

  resources :zombies do
  resources :brains
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


get '/appnuevis/cerebros', to:'brains#index', as:'brains'



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">AppZombies</li>
      <li>
        <a href="#">Despliega</a>
        <ul class="menu vertical">
        
        <%if user_signed_in? || admin_signed_in?%>
          <li><%= link_to 'Lista de Zombies', zombies_path %></li>
          <li><%= link_to 'Agrega Zombie', new_zombie_path %></li>
          
          <%else%>
          <li> "Error al acceder" </li>
          <%end%>
          
      </ul>
   
      </li>
   </ul>
     </div>
     

   <div class="top-bar-right">
  <ul class= "menu">
  <%if user_signed_in? || admin_signed_in? %>
  <%if user_signed_in? %>
  <li>Bienvenido(a) <%= current_user.email %></li>
  <%else%>
  <li>Bienvenido(a) <%= current_admin.email %></li>
  <%end%>
  <li><%= link_to "Editar Perfil", edit_user_registration_path%></li>
  <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
  <%else%>
  <li><%= link_to "Login", new_user_session_path %></li>
  <li><%= link_to "Registro", new_user_registration_path %></li>
  <%end%>
  
   </div>






<div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%=key%>"><%= value %></div>
      <% end %>
</div>



    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>